name: thinkz
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  page_transition: ^2.0.5
  json_serializable: ^6.5.4
  build_runner: ^2.1.10
  flutter_secure_storage: ^5.0.2
  http: ^0.13.4
  permission_handler: ^9.2.0
  flutter_screenutil: ^5.5.4
  json_annotation: ^4.7.0
  flutter_mapbox_navigation:
    path: ../
  location: ^4.4.0
  animated_text_kit: ^4.2.2
  dio: ^4.0.6
  flutter_polyline_points: ^1.0.0
  flutter_native_splash: ^2.2.12
  mapbox_gl: ^0.16.0
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.6
  carousel_slider: ^4.1.1
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
